### ISSUE TITLE
Center stats in homepage

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/hp-canadensys#10]
I would like the stats on the homepage to be centered on the word beside (e.g. occurrences, datasets, etc)
I had a look at the home.yml for https://hp-theme.gbif-staging.org/ and https://grscicoll.hp.gbif-staging.org/ but I don't understand where to set this parameter.

**Comment by MortenHofft** [comment]
I do not believe there is a parameter for it. But you can add custom css here https://github.com/gbif/hp-canadensys/blob/master/_sass/_main.scss

**Comment by CaroleSinou** [comment]
Ok.
I noticed that all the hosted portals I have looked have the stats centered on the word below, so I thought it was the default.
So it is not? Or, putting the main title on the left have also modified the way things are centered in the entire homepage?

**Comment by MortenHofft** [comment]
Yes the css in https://github.com/gbif/hp-canadensys/blob/master/_sass/_main.scss#L11 will influence many things. including the stats section.

**Comment by CaroleSinou** [comment]
I'll let them as they are.
Thanks!

**Comment by MortenHofft** [comment]
If you only want to style part of the page that is possible as well. You just need to be more specific in your selectors. Let me know if you need help with anythings specific.

Your header for example has a class called `floatingHero` you could use that in combination with `feature-content`?
E.e. `.home.floatingHero .feature-content` should be enough that only the first block is changed

**Comment by CaroleSinou** [comment]
Thanks Morten!
It worked :)
