### ISSUE TITLE
How to add space between logo in footer

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/hp-canadensys#14]
@MortenHofft , I have been scratching my head for a while now, and tried to implement the info found online, but nothing is working...
I have two logos in the footer, that are placed in the same block (column), but they always appear without space between them.
I am pretty sure the solution is simple, but I am stuck.
Can you help? (I am sure you can, just asking for the form)

**Comment by MortenHofft** [comment]
perhaps style the images in you scss folder?

```css
.footer-description img {
    margin-bottom: 24px;
}
```

**Comment by CaroleSinou** [comment]
Thanks Morten, 
It is working with your solution.

I'm curious, why is it not working with yaml styling (|+, |-, >+ and >-), as explained [here](https://yaml-multiline.info/#:~:text=Block%20Style%20Indicator%3A%20The%20block,right%20angle%20bracket%20(%20%3E%20).)
