### ISSUE TITLE
Stories (news items from GBIF) not showing the all events in the near future

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/hp-canadensys#15]
I have added the stories to the homepage, using a filter for Events only (https://canadensys.hp.gbif-staging.org/).
It works but the events occurring next week are not appearing in the 3 items shown (for example: Technical support hour for GBIF nodes: December 2023)
Is it a bug or have I missed something on my side?

Other question: is it possible to filter for event organized by GBIF only?

**Comment by MortenHofft** [comment]
Hi Carole, I suspect that is simply because the events aren't ordered. That should be an option if we want to continue with this

**Comment by MortenHofft** [comment]
> Other question: is it possible to filter for event organized by GBIF only?

As far as I can see we do not have any such data available in our cms
