### ISSUE TITLE
From vs About Canada

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/hp-canadensys#19]
**Is your feature request related to a problem? Please describe.**
We are currently showing data FROM Canada but some users are asking about the possibility to also see data ABOUT Canada.
This could be specifically interesting for our network as we are involved in an initiative to showcase Canadian biodiversity. The Canadensys portal could be used as the main portal for this type of data.

**Describe the solution you'd like**
A way to switch from the FROM predicate to ABOUT, like a button on the home page or in the search widget.

**Describe alternatives you've considered**
Another potential solution would be to have a second parallel portal with data about canada as the scope but this portal would just be used for the search widget, which could be integrated within the main one. I don't really know if it is possible and not a stupid idea.

**Comment by MortenHofft** [comment]
The problem with having multiple is that all these pages link to eachother. Say a dataset page will link to the occurrence search. And when there are multiple then I wouldn't know what to do at this point

Could you just expand the scope to be both? And then have a link in the navigation: data about + data from ? which essentially just sets the filters `country=CA` or `publishingCountry=CA`

Would that work for you? I've seen some other HP's do that, but cannot remember who just now.

A new special filter: FROM | ABOUT could probably also work. But it isn't something we have support for currently. I'm not entirely sure what a good implementation and UI would be either.

**Comment by CaroleSinou** [comment]
I did not realized it was that simple. Thanks!
I added buttons on the home page (Data from, Data about), with filters to publishingCountry=CA and country=CA
I have also modified the predicate. I think I get it right, but there are some discrepancies between the numbers available on gbif.org (data from : 148,603,556 in gbif, 146,926,903 in Canadensys). Do you know why?

**Comment by MortenHofft** [comment]
https://canadensys.hp.gbif-staging.org/occurrence/search?publishingCountry=CA&view=TABLE
says `148,622,636 results`

https://canadensys.hp.gbif-staging.org/occurrence/search?publishingCountry=CA&view=MAP
says `146,934,980 results with coordinates`

perhaps you looked at the map and the count for records with coordinates?
