### ISSUE TITLE
How to define where the title is displayed on homepage

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/hp-canadensys#2]
I would like to display the homepage title on the left side (or with text aligned on the left), as demonstrated on these demo portals: https://demo-tecala.hp.gbif-staging.org/, https://demo-nhc-dark.hp.gbif-staging.org/

I tried to find how to do so in the related gitHub repositories, but did not find anything helpful.
Could you explain it or indicates where it is specified in the different files for the demo portals mentioned above?

**Comment by thomasstjerne** [comment]
Hi @CaroleSinou 
I Think should be able to do so by adding styles to https://github.com/gbif/hp-canadensys/blob/master/_sass/_main.scss

The sites you point at has this:

`````
.home {
  .feature-content {
    text-align: start;
    margin-left: auto;
    margin-right: auto;
    width: $navbar-breakpoint;
    max-width: 100%;
  }
  .feature-description {
    margin: initial;
    padding: 0;
    width: 500px;
    p {
      font-weight: 500
    }
  }
  .feature-title {
    width: 500px;
    font-size: 4rem;
  }
}
`````
