### ISSUE TITLE
Beaty site vs Beaty in GRSciColl

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-canadensys#9]
https://canadensys.hp.gbif-staging.org/institution/search
The Beaty Biodiversity Museum is listed as the second largest institution. But "only" 43K records are in GBIF according to the matching.

But in reality we also have
https://beaty-biodiversity-museum.hp.gbif-staging.org/specimen/search
with almost 700K records.

I'm not sure how to best address that, but it looks odd.

**Comment by CaroleSinou** [comment]
The issue is coming from the fact that the institutionCode, institutionID, collectionCode and collectionID within the dataset are not the one registered on GrSciColl.
These datasets are published on Canadensys so I will update them.
Thanks for the heads-up :)

**Comment by MortenHofft** [comment]
When these things happen we have 2 ways to solve them. Fix the source dataset - I suppose that is the best solution if it is adding a stable ID.
Secondly we can add alternative codes and identifers to grscicoll through the registry ui. That is also a valid fix in many cases.

**Comment by CaroleSinou** [comment]
Test done on one dataset worked (by fixing source file).
The other datasets will be updated as well.
